# Generated by Django 4.0 on 2022-02-02 21:48

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('date_published', models.DateTimeField(verbose_name='Publishing date')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('slug', models.SlugField(max_length=350, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('date_published', models.DateTimeField(verbose_name='Publishing date')),
                ('original_date', models.CharField(blank=True, max_length=350)),
                ('annotation', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('book_name', models.CharField(blank=True, max_length=350)),
                ('publisher', models.CharField(blank=True, max_length=350)),
                ('publisher_city', models.CharField(blank=True, max_length=150)),
                ('publisher_year', models.CharField(blank=True, max_length=150)),
                ('isbn', models.CharField(blank=True, max_length=350)),
                ('link_url', models.CharField(blank=True, max_length=350)),
                ('lang', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to=books.models.get_image_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('categories', models.ManyToManyField(blank=True, to='books.Category')),
            ],
        ),
    ]
