# Generated by Django 4.0 on 2022-02-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='full_text',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='books.Keyword'),
        ),
    ]
