# Generated by Django 4.0 on 2022-02-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='full_text',
            field=models.TextField(blank=True),
        ),
    ]
