# Generated by Django 4.0 on 2022-02-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_full_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(unique=True)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='original_date',
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.ManyToManyField(blank=True, to='books.Year'),
        ),
    ]
