# Generated by Django 4.0 on 2022-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='books',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
